BEGIN TRANSACTION;

CREATE SCHEMA local ;
CREATE SCHEMA history ;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA local ;
CREATE EXTENSION IF NOT EXISTS ltree WITH SCHEMA local ;
CREATE EXTENSION IF NOT EXISTS temporal_tables WITH SCHEMA local;

COMMIT;
